Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2020-12, with the labels that each got.

#383 PCA Modifications
  daal4py/sklearn/decomposition/__init__.py
  daal4py/sklearn/decomposition/_pca.py
  daal4py/sklearn/decomposition/_pca_0_21.py
  daal4py/sklearn/decomposition/_pca_0_22.py
  daal4py/sklearn/decomposition/_pca_0_23.py
  daal4py/sklearn/decomposition/pca.py
  daal4py/sklearn/monkeypatch/dispatcher.py
Labels: sklearn-patch

#413 Update branch for testing nightly
  .circleci/config.yml
Labels: infra

#415 Replace oneDAL moments on var from numpy for SVM
  daal4py/sklearn/svm/_svm_0_21.py
  daal4py/sklearn/svm/_svm_0_22.py
  daal4py/sklearn/svm/_svm_0_23.py
Labels: sklearn-patch

#418 Change distributed dbscan communication
  setup.py
  src/dist_dbscan.h
Labels: distributed

#422 Update win version for dpc++ toolkit
  azure-pipelines.yml
  conda-recipe/bld.bat
  conda-recipe/conda_build_config.yaml
  conda-recipe/meta.yaml
Labels: infra

#424 [Part2] Clean & fix scikit-learn testing
  .circleci/config.yml
  .circleci/setup_env.sh
  deselected_tests.yaml
Labels: infra

#428 Fix nightly testing
  .circleci/config.yml
  .circleci/setup_env.sh
Labels: infra

#120 Tests for batch DBSCAN
  daal4py/sklearn/cluster/__init__.py
  daal4py/sklearn/cluster/tests/test_dbscan.py
  daal4py/sklearn/neighbors/tests/test_kneighbors.py
Labels: testing

#431 [DOC] Updated links, fixed spelling
  doc/algorithms.rst
  doc/index.rst
  doc/scaling.rst
  doc/sklearn.rst
Labels: documentation

#434 Add reference for articles on Medium
  README.md
Labels: documentation

#432 Scikit-learn tests tix for patching of version 0.21 & 0.22
  daal4py/sklearn/decomposition/_pca.py
  daal4py/sklearn/ensemble/__init__.py
  daal4py/sklearn/ensemble/_forest.py
  daal4py/sklearn/ensemble/forest.py
  daal4py/sklearn/manifold/_t_sne.py
  daal4py/sklearn/metrics/_ranking.py
  daal4py/sklearn/monkeypatch/dispatcher.py
  deselected_tests.yaml
Labels: sklearn-patch

#435 Update scikit-learn version for support with daal4py
  azure-pipelines.yml
  daal4py/sklearn/monkeypatch/dispatcher.py
Labels: sklearn-patch

#439 Fix check sklearn estimators for sklearn like interfaces
  daal4py/sklearn/ensemble/AdaBoostClassifier.py
  daal4py/sklearn/ensemble/GBTDAAL.py
  daal4py/sklearn/ensemble/decision_forest.py
  tests/test_estimators.py
Labels: sklearn-patch

#437 Initial GPU docs
  README.md
  doc/index.rst
Labels: documentation

#440 Fix knn tests for 2020u3
  daal4py/sklearn/ensemble/tests/test_decision_forest.py
  daal4py/sklearn/neighbors/tests/test_kneighbors.py
Labels: testing

#438 Fix of kmeans for scikit-learn-0.24 testing
  daal4py/sklearn/cluster/_k_means_0_23.py
  daal4py/sklearn/linear_model/_coordinate_descent_0_23.py
  daal4py/sklearn/linear_model/_logistic_path_0_22.py
Labels: sklearn-patch

#443 Enable pytest of scikit-learn patching algorithm for MAC OS
  azure-pipelines.yml
  daal4py/sklearn/neighbors/tests/test_kneighbors.py
Labels: infra, testing

#442 Update docs with GPU support
  _sources/algorithms.rst.txt
  _sources/index.rst.txt
  _sources/scaling.rst.txt
  _sources/sklearn.rst.txt
  _static/basic.css
  _static/css/badge_only.css
  _static/css/fonts/Roboto-Slab-Bold.woff
  _static/css/fonts/Roboto-Slab-Bold.woff2
  _static/css/fonts/Roboto-Slab-Regular.woff
  _static/css/fonts/Roboto-Slab-Regular.woff2
  _static/css/fonts/fontawesome-webfont.eot
  _static/css/fonts/fontawesome-webfont.svg
  _static/css/fonts/fontawesome-webfont.ttf
  _static/css/fonts/fontawesome-webfont.woff
  _static/css/fonts/fontawesome-webfont.woff2
  _static/css/fonts/lato-bold-italic.woff
  _static/css/fonts/lato-bold-italic.woff2
  _static/css/fonts/lato-bold.woff
  _static/css/fonts/lato-bold.woff2
  _static/css/fonts/lato-normal-italic.woff
  _static/css/fonts/lato-normal-italic.woff2
  _static/css/fonts/lato-normal.woff
  _static/css/fonts/lato-normal.woff2
  _static/css/theme.css
  _static/doctools.js
  _static/fonts/FontAwesome.otf
  _static/fonts/Roboto-Slab-Bold.woff
  _static/fonts/Roboto-Slab-Bold.woff2
  _static/fonts/Roboto-Slab-Light.woff
  _static/fonts/Roboto-Slab-Light.woff2
  _static/fonts/Roboto-Slab-Regular.woff
  _static/fonts/Roboto-Slab-Regular.woff2
  _static/fonts/Roboto-Slab-Thin.woff
  _static/fonts/Roboto-Slab-Thin.woff2
  _static/fonts/lato-bold-italic.woff
  _static/fonts/lato-bold-italic.woff2
  _static/fonts/lato-bold.woff
  _static/fonts/lato-bold.woff2
  _static/fonts/lato-normal-italic.woff
  _static/fonts/lato-normal-italic.woff2
  _static/fonts/lato-normal.woff
  _static/fonts/lato-normal.woff2
  _static/js/badge_only.js
  _static/js/html5shiv-printshiv.min.js
  _static/js/html5shiv.min.js
  _static/js/theme.js
  _static/pygments.css
  _static/searchtools.js
  algorithms.html
  contents.html
  data.html
  examples.html
  genindex.html
  index.html
  objects.inv
  scaling.html
  search.html
  searchindex.js
  sklearn.html
  streaming.html
Labels: documentation, duplicate

#441 Introduce requerements file for documentation
  .ci/pipeline/ci.yml
  .ci/pipeline/docs.yml
  doc/requirements.txt
Labels: documentation, infra

#446 Remove moved pipeline
  README.md
  azure-pipelines.yml
Labels: infra

#448 Update README.md - Add new article and update a support of algorithms in sklearn patch
  README.md
Labels: documentation

#417 Run-to-run stability tests
  daal4py/sklearn/test/test_run_to_run_stability_tests.py
Labels: testing
