Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2020-10, with the labels that each got.

#324 Fixed code quality issues regarding spacing, style and imports
  conda-recipe/run_test.sh
  daal4py/sklearn/ensemble/__init__.py
  daal4py/sklearn/linear_model/_linear_0_21.py
  daal4py/sklearn/linear_model/_linear_0_22.py
  daal4py/sklearn/linear_model/_linear_0_23.py
  daal4py/sklearn/linear_model/_ridge_0_21.py
  daal4py/sklearn/linear_model/_ridge_0_22.py
  daal4py/sklearn/monkeypatch/dispatcher.py
  examples/naive_bayes_batch.py
  examples/naive_bayes_spmd.py
  examples/naive_bayes_streaming.py
  generator/gen_daal4py.py
  src/dist_dbscan.h
  src/npy4daal.h
  src/transceiver.cpp
  src/tree_visitor.h
Labels: hacktoberfest-accepted

#332 Remove several unnecessary "else" after "return"
  .circleci/deselect_tests.py
  daal4py/__main__.py
  daal4py/sklearn/_utils.py
  daal4py/sklearn/cluster/_dbscan_0_21.py
  daal4py/sklearn/cluster/_dbscan_0_22.py
  daal4py/sklearn/cluster/_k_means_0_21.py
  daal4py/sklearn/cluster/_k_means_0_22.py
  daal4py/sklearn/cluster/_k_means_0_23.py
  daal4py/sklearn/decomposition/_pca_0_21.py
  daal4py/sklearn/decomposition/_pca_0_22.py
  daal4py/sklearn/decomposition/_pca_0_23.py
  daal4py/sklearn/ensemble/GBTDAAL.py
  daal4py/sklearn/ensemble/_forest_0_23.py
  daal4py/sklearn/ensemble/decision_forest.py
  daal4py/sklearn/linear_model/_coordinate_descent_0_23.py
  daal4py/sklearn/linear_model/_linear_0_21.py
  daal4py/sklearn/linear_model/_linear_0_22.py
  daal4py/sklearn/linear_model/_linear_0_23.py
  daal4py/sklearn/linear_model/_ridge_0_21.py
  daal4py/sklearn/linear_model/_ridge_0_22.py
  daal4py/sklearn/model_selection/_split.py
  daal4py/sklearn/neighbors/knn.py
  examples/run_examples.py
  examples/sycl/sklearn_sycl.py
  generator/gen_daal4py.py
  generator/parse.py
  generator/wrapper_gen.py
Labels: hacktoberfest-accepted

#338 Resolve several codefactor.io issues
  daal4py/__init__.py
  daal4py/sklearn/cluster/_dbscan_0_21.py
  daal4py/sklearn/cluster/_dbscan_0_22.py
  daal4py/sklearn/decomposition/_pca_0_21.py
  daal4py/sklearn/decomposition/_pca_0_22.py
  daal4py/sklearn/decomposition/_pca_0_23.py
  daal4py/sklearn/ensemble/AdaBoostClassifier.py
  daal4py/sklearn/ensemble/GBTDAAL.py
  daal4py/sklearn/linear_model/_coordinate_descent_0_21.py
  daal4py/sklearn/linear_model/_coordinate_descent_0_23.py
  daal4py/sklearn/svm/_svm_0_21.py
  daal4py/sklearn/svm/_svm_0_22.py
  daal4py/sklearn/svm/_svm_0_23.py
  daal4py/sklearn/tree/decision_tree.py
  examples/decision_forest_classification_traverse_batch.py
  examples/decision_forest_regression_traverse_batch.py
  examples/decision_tree_classification_traverse_batch.py
  examples/decision_tree_regression_traverse_batch.py
  examples/gradient_boosted_classification_traverse_batch.py
  examples/gradient_boosted_regression_traverse_batch.py
  examples/pca_spmd.py
  examples/run_examples.py
  generator/format.py
  setup.py
Labels: hacktoberfest-accepted

#341 Resolve minor codefactor.io issues
  daal4py/sklearn/neighbors/_base.py
  generator/gen_daal4py.py
  generator/wrapper_gen.py
Labels: hacktoberfest-accepted

#340 2020-u3 docs update
  _modules/index.html
  _sources/sklearn.rst.txt
  _static/basic.css
  _static/pygments.css
  _static/searchtools.js
  algorithms.html
  contents.html
  data.html
  examples.html
  genindex.html
  index.html
  scaling.html
  search.html
  searchindex.js
  sklearn.html
  streaming.html
Labels: documentation

#363 Fix problem with patching for SVC
  .circleci/config.yml
  daal4py/sklearn/svm/_svm_0_21.py
  daal4py/sklearn/svm/_svm_0_22.py
  daal4py/sklearn/svm/_svm_0_23.py
  deselected_tests.yaml
Labels: sklearn-patch

#336 Model builder for logistic regression & patching sklearn
  daal4py/sklearn/linear_model/_logistic_path_0_22.py
  daal4py/sklearn/monkeypatch/dispatcher.py
  examples/log_reg_model_builder.py
  examples/run_examples.py
  generator/gen_daal4py.py
  generator/parse.py
  src/gbt_model_builder.h
  src/gbt_model_builder.pyx
  src/log_reg_model_builder.h
  src/log_reg_model_builder.pyx
  tests/test_logistic_regression_model_builder.py
Labels: sklearn-patch

#368 Fix n_jobs problem in LogisticRegression
  daal4py/sklearn/linear_model/_logistic_path_0_22.py
Labels: sklearn-patch
