Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2021-01, with the labels that each got.

#451 Update README.md - minor update for examples
  README.md
Labels: documentation

#452 Deselect failed LogReg test
  .ci/pipeline/ci.yml
  deselected_tests.yaml
Labels: testing

#436 Changing SVD to Covariance in PCA
  daal4py/sklearn/decomposition/_pca.py
  deselected_tests.yaml
Labels: sklearn-patch

#456 Removing Unnecessary Imports
  daal4py/sklearn/monkeypatch/dispatcher.py
Labels: bug

#457 PCA Bug Fix
  daal4py/sklearn/decomposition/_pca.py
  deselected_tests.yaml
Labels: bug

#455 Fix supported types of KNN predict_proba
  daal4py/sklearn/neighbors/_base.py
Labels: sklearn-patch

#458 Adding a setup configuration file
  setup.cfg
  setup.py
Labels: infra

#461 Add logging & fix patch of pairwise_distances
  daal4py/sklearn/monkeypatch/_pairwise_0_21.py
  daal4py/sklearn/monkeypatch/_pairwise_0_22.py
  daal4py/sklearn/monkeypatch/dispatcher.py
Labels: bug, sklearn-patch

#462 Update install_windows.bat for download dpcpp compiler
  .ci/pipeline/ci.yml
  .ci/scripts/install_windows.bat
Labels: infra

#454 Improve run-to-run tests
  daal4py/sklearn/test/test_run_to_run_stability_tests.py
Labels: testing

#463 Reduce tests for scikit-learn
  .circleci/compare_runs.py
  .circleci/config.yml
  .circleci/deselect_tests.py
  .circleci/run_and_compare.sh
  deselected_tests.yaml
Labels: infra, testing

#464 Fix memory leak in Numeric Table creation
  src/daal4py.cpp
Labels: bug

#467 Add support section to README
  README.md
Labels: documentation

#473 Add .mergify.yml
  .mergify.yml
Labels: infra

#470 Fix unittest issue
  .ci/pipeline/ci.yml
  conda-recipe/meta.yaml
  tests/run_tests.py
Labels: testing

#475 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#472 Enable pytest of scikit-learn patching algorithm for MAC OS
  .ci/pipeline/ci.yml
Labels: bug, testing

#474 Fix for scikit-learn unpatching
  daal4py/sklearn/__init__.py
  daal4py/sklearn/monkeypatch/dispatcher.py
  daal4py/sklearn/monkeypatch/tests/test_monkeypatch.py
  tests/test_monkeypatch.py
Labels: bug, testing

#477 Update pipline for docs
  .ci/pipeline/ci.yml
  .ci/pipeline/docs.yml
  .gitattributes
  conda-recipe/build.sh
  conda-recipe/run_test.sh
  examples/svm_multiclass_batch.py
  requirements-dev.txt
  requirements-doc.txt
  requirements-test.txt
Labels: bug, documentation

#479 Fix run-to-run stability for Random Forest
  daal4py/sklearn/ensemble/_forest.py
  daal4py/sklearn/test/test_run_to_run_stability_tests.py
Labels: bug, sklearn-patch
