Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2021-12, with the labels that each got.

#897 Fix linux_DPCPP job for public CI
  .ci/pipeline/ci.yml
Labels: infra

#900 Update xpu tests runner to support deselected tests
  .circleci/deselect_tests.py
  .circleci/run_xpu_tests.py
Labels: infra

#898 Add memory requirements to docs
  doc/sources/index.rst
  doc/sources/memory-requirements.rst
Labels: documentation

#910 Update installation
  INSTALL.md
  doc/sources/conf.py
  doc/sources/installation.rst
  doc/sources/system-requirements.rst
  requirements-doc.txt
Labels: documentation

#905 Remove patch rpath for release CI
  .ci/pipeline/release.yml
Labels: infra

#881 Add new deselected tests for gpu part
  deselected_tests.yaml
Labels: testing
