Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2021-08, with the labels that each got.

#763 Minor updates for readme and documentation
  README.md
  doc/sources/get_started.rst
Labels: documentation

#765 [Kmeans] Clean deselect tests
  deselected_tests.yaml
Labels: sklearn-patch

#754 Global patching for scikit-learn
  .ci/pipeline/ci.yml
  .ci/scripts/test_global_patch.py
  setup_sklearnex.py
  sklearnex/dispatcher.py
  sklearnex/glob/__main__.py
  sklearnex/glob/dispatcher.py
Labels: sklearn-patch

#768 Train_test_split fix and test for specific subset sizes
  daal4py/sklearn/model_selection/_split.py
  daal4py/sklearn/model_selection/tests/test_split.py
Labels: bug

#766 [RF] Partial revert for fixing the test
  daal4py/sklearn/ensemble/_forest.py
  daal4py/sklearn/utils/validation.py
Labels: bug, sklearn-patch
