Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2021-11, with the labels that each got.

#855 Add wait to memcpy and update context
  onedal/datatypes/data_conversion.cpp
Labels: bug, oneAPI

#868 Cast to float in SVC test due to fail on GPU
  onedal/svm/tests/test_svc.py
Labels: testing

#880 [DOCS] Update patching options and daal4py install guide
  README.md
  daal4py/INSTALL.md
  doc/sources/patching/patching-options.rst
  doc/sources/what-is-patching.rst
Labels: documentation

#828 Update atol in sycl linreg example
  examples/daal4py/sycl/linear_regression_batch.py
Labels: examples
