Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2021-03, with the labels that each got.

#543 Return SVM stability tests
  daal4py/sklearn/test/test_run_to_run_stability_tests.py
Labels: testing

#549 Update INSTALL.md for install and develop mode
  INSTALL.md
Labels: documentation

#550 USM support in sycl_buffer
  daal4py/oneapi/__init__.py
  doc/make.bat
  dpcppcompiler.py
  examples/sycl/dbscan_batch.py
  examples/sycl/kmeans_batch.py
  examples/sycl/svm_batch.py
  setup.py
  src/oneapi/oneapi.h
  src/oneapi/oneapi.pyx
  src/oneapi/oneapi_backend.cpp
  src/oneapi/oneapi_backend.h
Labels: enhancement, oneAPI

#548 Refactoring of deselected tests
  deselected_tests.yaml
Labels: testing

#555 Add blog "Intel Gives Scikit-Learn the Performance Boost Data Scientists Need"
  README.md
Labels: documentation

#547 XGBoost Examples
  examples/XGBoost_Performance.ipynb
  examples/XGBoost_d4p_prediction.ipynb
Labels: examples

#553 Estimators memory leak testing
  daal4py/sklearn/_utils.py
  daal4py/sklearn/test/test_memory_usage.py
  tests/test_memory_usage.py
Labels: testing

#509 CI for coverity
  .ci/pipeline/coverity.yml
  README.md
Labels: infra

#558 Revert test_classifier_chain_tuple_order in deselect due unstable result RF in <2021.2
  deselected_tests.yaml
Labels: testing

#557 Remove boosting from req, revert unstable sklearn tests
  .ci/pipeline/ci.yml
  daal4py/sklearn/monkeypatch/tests/_models_info.py
  deselected_tests.yaml
  requirements-test.txt
Labels: testing

#560 Fix legal issue in deselected_tests.yaml
  deselected_tests.yaml
Labels: documentation

#559 Fix of test_check_n_features_in_after_fitting in deselect tests
  daal4py/sklearn/cluster/_dbscan_0_22.py
  daal4py/sklearn/cluster/_k_means_0_22.py
  daal4py/sklearn/cluster/_k_means_0_23.py
  daal4py/sklearn/decomposition/_pca.py
  daal4py/sklearn/ensemble/_forest.py
  daal4py/sklearn/linear_model/_coordinate_descent_0_23.py
  daal4py/sklearn/linear_model/_linear_0_23.py
  daal4py/sklearn/linear_model/_logistic_path_0_22.py
  daal4py/sklearn/linear_model/_ridge_0_22.py
  daal4py/sklearn/neighbors/_base.py
  daal4py/sklearn/neighbors/_classification.py
  deselected_tests.yaml
Labels: sklearn-patch

#554 Create scikit-learn-intelex package
  .circleci/config.yml
  .circleci/run_and_compare.sh
  .gitignore
  INSTALL.md
  README.md
  daal4py/__init__.py
  daal4py/sklearn/_utils.py
  daal4py/sklearn/monkeypatch/dispatcher.py
  doc/third-party-programs-sklearnex.txt
  setup_sklearnex.cfg
  setup_sklearnex.py
  sklearnex/__init__.py
  sklearnex/__main__.py
  sklearnex/_utils.py
  sklearnex/dispatcher.py
Labels: infra

#566 Appropriate error handling for LightGBM model converter
  src/gbt_convertors.pyx
Labels: bug, model builders

#562 [Deselected tests] Part 2
  .circleci/deselect_tests.py
  .circleci/run_and_compare.sh
  daal4py/sklearn/ensemble/_forest.py
  deselected_tests.yaml
Labels: sklearn-patch, testing

#573 Fix deprecation messages for daal4py
  daal4py/sklearn/_utils.py
  daal4py/sklearn/monkeypatch/dispatcher.py
  setup_sklearnex.py
  sklearnex/_utils.py
Labels: sklearn-patch

#570 Add tests for sklearnex package
  sklearnex/tests/_models_info.py
  sklearnex/tests/test_monkeypatch.py
  sklearnex/tests/test_patching.py
  sklearnex/tests/utils/_launch_algorithms.py
Labels: testing

#580 Enable sklearnex tests to public ci
  .ci/pipeline/ci.yml
Labels: infra, testing

#582 Fix import sklearnex problem
  sklearnex/dispatcher.py
Labels: sklearn-patch

#565 Create readme for sklearnex
  INSTALL.md
  README.md
  daal4py/INSTALL.md
  daal4py/README.md
Labels: documentation

#539 define versions for different pythons
  requirements-test.txt
Labels: infra

#593 Updating renovate config to allow not pinnin numpy dep
  .github/renovate.json
Labels: infra

#586 Add blog "Intel Gives Scikit-Learn the Performance Boost Data Scientists Need"
  README.md
  daal4py/README.md
Labels: documentation

#597 Move picture to doc directory
  doc/IDP scikit-learn accelearation compared with stock scikit-learn.png
Labels: documentation
