Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2021-02, with the labels that each got.

#483 Add new badgen for discussion
  README.md
Labels: documentation

#486 Fix gpu example
  examples/sycl/kmeans_batch.py
Labels: bug

#487 Create CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement

#476 Continue of fix unitest issue
  conda-recipe/meta.yaml
  conda-recipe/run_test.sh
  tests/run_tests.py
Labels: testing

#489 Fix search of pip_requirements for renovate bot
  .github/renovate.json
  renovate.json
Labels: infra

#478 Memory leak tests
  tests/test_memory_usage.py
Labels: testing

#491 Fix typo in renovate.json - added missing bracket
  .github/renovate.json
Labels: bug

#497 Update readme and docs for support versions
  INSTALL.md
  README.md
  doc/_static/style.css
  doc/conf.py
  doc/index.rst
  doc/sklearn.rst
Labels: documentation

#500 Update docs from PR #497
  .buildinfo
  _modules/index.html
  _sources/index.rst.txt
  _sources/sklearn.rst.txt
  _static/documentation_options.js
  _static/style.css
  algorithms.html
  contents.html
  data.html
  examples.html
  genindex.html
  index.html
  objects.inv
  scaling.html
  search.html
  searchindex.js
  sklearn.html
  streaming.html
Labels: documentation

#459 PCA Patching Hotspots Fix
  daal4py/sklearn/decomposition/_pca.py
Labels: sklearn-patch

#501 Enable Run-to-Run Tests for PCA
  daal4py/sklearn/test/test_run_to_run_stability_tests.py
Labels: testing

#496 Testing of patching algorithms
  conda-recipe/run_test.sh
  daal4py/sklearn/monkeypatch/tests/_models_info.py
  daal4py/sklearn/monkeypatch/tests/test_patching.py
  daal4py/sklearn/monkeypatch/tests/utils/_launch_algorithms.py
Labels: testing

#505 Fix roc_auc supported types
  daal4py/sklearn/metrics/_ranking.py
  daal4py/sklearn/monkeypatch/tests/_models_info.py
  daal4py/sklearn/monkeypatch/tests/test_patching.py
Labels: sklearn-patch

#504 Changing of 'auto' Strategy in PCA
  daal4py/sklearn/decomposition/_pca.py
Labels: sklearn-patch

#506 Integrate hist method of Random Forest
  daal4py/sklearn/ensemble/_forest.py
  doc/algorithms.rst
  doc/examples.rst
  examples/decision_forest_classification_default_dense_batch.py
  examples/decision_forest_classification_hist_batch.py
  examples/decision_forest_classification_traverse_batch.py
  examples/decision_forest_regression_default_dense_batch.py
  examples/decision_forest_regression_hist_batch.py
  examples/decision_forest_regression_traverse_batch.py
  examples/run_examples.py
  examples/sycl/decision_forest_classification_hist_batch.py
  examples/sycl/decision_forest_regression_hist_batch.py
  tests/test_examples.py
Labels: sklearn-patch

#513 Change paths in README file
  README.md
Labels: documentation

#510 Enable DPC++ compiler support on Windows platform
  conda-recipe/bld.bat
  dpcppcompiler.py
  setup.py
Labels: infra

#515 Fix generators for not exist models
  generator/gen_daal4py.py
Labels: bug

#522 Decision Forest: fix daal4py examples
  examples/sycl/decision_forest_classification_hist_batch.py
  examples/sycl/decision_forest_regression_hist_batch.py
Labels: examples

#520 Fix roc auc failures
  daal4py/sklearn/metrics/_ranking.py
  daal4py/sklearn/monkeypatch/tests/utils/_launch_algorithms.py
Labels: bug

#517 output sycl and devices availability status to logs
  examples/run_examples.py
Labels: examples

#518 Fix test patching on python 3.6
  daal4py/sklearn/monkeypatch/tests/test_patching.py
  daal4py/sklearn/monkeypatch/tests/utils/_launch_algorithms.py
Labels: bug, testing

#488 Modify building daal4py for wheel packages
  daal4py/__init__.py
  requirements.txt
  setup.py
Labels: infra

#521 Change DPC++ compiler to clang++ in building scripts.
  conda-recipe/bld.bat
  conda-recipe/build.sh
  dpcppcompiler.py
  setup.py
Labels: infra

#524 Extend output in memory test
  tests/test_memory_usage.py
Labels: testing

#526 Enable daal4py to PyPI for mac os - 3.9
  README.md
  doc/index.rst
Labels: documentation

#527 Add test_from_model to deselected_tests.yaml for reduce scope
  deselected_tests.yaml
Labels: testing

#525 Remove compiler flags from build.sh for osx
  .ci/pipeline/ci.yml
  conda-recipe/build.sh
Labels: infra

#534 Fix random forest API for scikit-learn 0.21
  daal4py/sklearn/ensemble/_forest.py
Labels: bug, sklearn-patch

#535 Removing Moments from K-Means Init
  daal4py/sklearn/cluster/_k_means_0_21.py
  daal4py/sklearn/cluster/_k_means_0_22.py
  daal4py/sklearn/cluster/_k_means_0_23.py
Labels: sklearn-patch

#516 DF: fix tests and Sklearn patching
  daal4py/sklearn/ensemble/_forest.py
  daal4py/sklearn/ensemble/tests/test_decision_forest.py
  deselected_tests.yaml
Labels: testing

#533 Disable SVC run-to-run tests for green testing
  daal4py/sklearn/test/test_run_to_run_stability_tests.py
Labels: testing

#536 change modin conversion condition
  generator/wrapper_gen.py
Labels: enhancement

#542 Fix type for disable sklearn tests
  deselected_tests.yaml
Labels: bug, testing
