Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2021-06, with the labels that each got.

#671 Fix problem with runtime error with CPU device
  onedal/common/backend/compute.h
  onedal/common/backend/infer.h
  onedal/common/backend/train.h
Labels: bug

#672 Fix random stability for tests to random forest
  daal4py/sklearn/ensemble/tests/test_decision_forest.py
Labels: bug

#673 Fix cache size and shrinking parameters in onedal iface
  onedal/svm/backend/svm_py.cpp
  onedal/svm/svm.py
  onedal/svm/svm.pyx
Labels: bug, onedal iface

#676 Add Superior Machine Learning Performance on the Latest Intel Xeon
  README.md
Labels: documentation

#677 [rls] Fix cache size and shrinking parameters in onedal iface (#673)
  onedal/svm/backend/svm_py.cpp
  onedal/svm/svm.py
  onedal/svm/svm.pyx
Labels: duplicate

#680 Add examples for sklearnex
  .ci/pipeline/ci.yml
  .ci/pipeline/coverity.yml
  .ci/pipeline/nightly.yml
  examples/daal4py/daal4py_data_science.ipynb
  examples/notebooks/svc_mnsit.ipynb
Labels: examples

#684 Fill fields in notebook for KNN
  examples/notebooks/knn_mnist.ipynb
Labels: examples

#687 Add new perf data for sklearnex
  README.md
  doc/scikit-learn-acceleration-2021.2.3.PNG
  doc/sources/index.rst
Labels: documentation

#697 Fix path to plot of perf at Readme
  README.md
Labels: bug, documentation

#696 PCA and LinReg sycl examples changed to use float32 algorithm versions
  examples/daal4py/sycl/linear_regression_batch.py
  examples/daal4py/sycl/pca_batch.py
Labels: examples

#654 Fix memory test due to wrong leak in Logistic Regression
  sklearnex/tests/test_memory_usage.py
Labels: testing

#695 [rls] PCA and LinReg sycl examples changed to use float32 algorithm versions
  examples/sycl/linear_regression_batch.py
  examples/sycl/pca_batch.py
Labels: bug

#699 Clean deprecations before 1.0 [RF]
  daal4py/sklearn/ensemble/_forest.py
  deselected_tests.yaml
Labels: sklearn-patch

#698 Clean deprecations before 1.0 [RF]
  daal4py/sklearn/ensemble/_forest.py
  deselected_tests.yaml
Labels: testing

#694 Replace mnist to adult dataset for SVM example
  .ci/pipeline/nightly.yml
  examples/notebooks/knn_mnist.ipynb
  examples/notebooks/logistictic_regression_cifar.ipynb
  examples/notebooks/random_forest_yolanda.ipynb
  examples/notebooks/svc_adult.ipynb
Labels: examples

#700 Clean before scikit-learn 1.0 - Remove 0.21
  daal4py/sklearn/cluster/_dbscan_0_21.py
  daal4py/sklearn/cluster/_k_means_0_21.py
  daal4py/sklearn/cluster/dbscan.py
  daal4py/sklearn/cluster/k_means.py
  daal4py/sklearn/ensemble/_forest.py
  daal4py/sklearn/linear_model/_coordinate_descent_0_22.py
  daal4py/sklearn/linear_model/_linear_0_21.py
  daal4py/sklearn/linear_model/_ridge_0_21.py
  daal4py/sklearn/linear_model/coordinate_descent.py
  daal4py/sklearn/linear_model/linear.py
  daal4py/sklearn/linear_model/logistic_path.py
  daal4py/sklearn/linear_model/ridge.py
  daal4py/sklearn/neighbors/_unsupervised.py
  daal4py/sklearn/svm/_svm_0_21.py
  daal4py/sklearn/svm/svm.py
Labels: sklearn-patch

#702 Change limit of memory in tests due to warnings on macOS
  sklearnex/tests/test_memory_usage.py
Labels: testing

#701 Sigmoid Kernel
  daal4py/sklearn/svm/_svm_0_23.py
  onedal/prims/__init__.py
  onedal/prims/backend/kernel_functions_py.cpp
  onedal/prims/backend/kernel_functions_py.h
  onedal/prims/kernel_functions.pxi
  onedal/prims/kernel_functions.py
  onedal/prims/kernel_functions.pyx
  onedal/prims/tests/test_kernel_functions.py
  onedal/svm/backend/svm_py.cpp
  onedal/svm/tests/test_csr_svm.py
  onedal/svm/tests/test_nusvr.py
  onedal/svm/tests/test_svc.py
  onedal/svm/tests/test_svr.py
  sklearnex/svm/nusvc.py
  sklearnex/svm/nusvr.py
  sklearnex/svm/svc.py
  sklearnex/svm/svr.py
Labels: onedal iface, sklearn-patch

#704 Clean deprecations before scikit-learn 1.0 [Coordinate descent]
  daal4py/sklearn/linear_model/_coordinate_descent_0_23.py
Labels: sklearn-patch

#693 Update docs for 2021.3 release
  README.md
  doc/sources/_static/scikit-learn-acceleration-2021.2.3.PNG
  doc/sources/algorithms.rst
  doc/sources/conf.py
  doc/sources/get_started.rst
  doc/sources/index.rst
Labels: documentation

#706 [gh-pages] Update docs to 2021.3
  .buildinfo
  _images/scikit-learn-acceleration-2021.2.3.PNG
  _sources/algorithms.rst.txt
  _sources/contents.rst.txt
  _sources/get_started.rst.txt
  _sources/gpu.rst.txt
  _sources/index.rst.txt
  _sources/verbose.rst.txt
  _static/basic.css
  _static/scikit-learn-acceleration-2021.2.3.PNG
  _static/searchtools.js
  _static/underscore-1.13.1.js
  _static/underscore.js
  algorithms.html
  contents.html
  genindex.html
  get_started.html
  gpu.html
  index.html
  search.html
  searchindex.js
  verbose.html
Labels: documentation, duplicate

#692 Add releases packages to Azure
  .ci/pipeline/release.yml
  .ci/scripts/gen_release_jobs.py
Labels: infra

#707 [RF] Code literals in deprecation
  daal4py/sklearn/ensemble/_forest.py
Labels: sklearn-patch

#708 Increase timeout to Nightly job
  .ci/pipeline/nightly.yml
Labels: infra
