Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2021-04, with the labels that each got.

#585 Device information in patching, option to fallback on host
  README.md
  daal4py/oneapi/__init__.py
  daal4py/sklearn/_utils.py
  daal4py/sklearn/monkeypatch/tests/test_patching.py
  doc/daal4py/sklearn.rst
  doc/sources/verbose.rst
  generator/wrapper_gen.py
  sklearnex/_utils.py
  sklearnex/tests/test_patching.py
  src/oneapi/oneapi.pyx
  src/oneapi/oneapi_backend.cpp
  src/oneapi/oneapi_backend.h
Labels: oneAPI, sklearn-patch

#598 Fix description for support parameters for sklearn patching algorithms
  README.md
Labels: documentation

#601 Fix "_y" attribute behavior for Nearest Neighbors
  daal4py/sklearn/neighbors/_base.py
Labels: bug

#606 Switch dpcpp compiler to 2021.2 for windows
  .ci/pipeline/ci.yml
Labels: infra

#608 Clean deselect run-to-run tests
  daal4py/sklearn/test/test_run_to_run_stability_tests.py
Labels: testing

#612 Fix nightly testing
  .circleci/config.yml
Labels: testing

#610 Disable Logistic Regression example until fix
  examples/sycl/log_reg_binary_dense_batch.py
  tests/test_examples.py
Labels: testing

#609 Fix description for support parameters for sklearn patching algorithm for docs
  doc/sources/algorithms.rst
Labels: documentation

#614 Adding links for daal4py in docs
  README.md
  doc/sources/index.rst
Labels: documentation

#617 Fix copyright
  .ci/pipeline/ci.yml
  .ci/pipeline/coverity.yml
  .circleci/compare_runs.py
  .circleci/config.yml
  .circleci/deselect_tests.py
  .circleci/run_and_compare.sh
  .circleci/setup_env.sh
  .mergify.yml
  conda-recipe/bld.bat
  conda-recipe/build.sh
  conda-recipe/conda_build_config.yaml
  conda-recipe/meta.yaml
  conda-recipe/run_test.bat
  conda-recipe/run_test.sh
  daal4py/sklearn/test/test_memory_usage.py
  deselected_tests.yaml
  doc/Makefile
  doc/daal4py/Makefile
  doc/daal4py/algorithms.rst
  doc/daal4py/conf.py
  doc/daal4py/contents.rst
  doc/daal4py/data.rst
  doc/daal4py/examples.rst
  doc/daal4py/index.rst
  doc/daal4py/make.bat
  doc/daal4py/scaling.rst
  doc/daal4py/sklearn.rst
  doc/daal4py/streaming.rst
  doc/make.bat
  doc/sources/algorithms.rst
  doc/sources/conf.py
  doc/sources/contents.rst
  doc/sources/get_started.rst
  doc/sources/gpu.rst
  doc/sources/index.rst
  doc/sources/verbose.rst
  src/gettree.pyx
  src/lbfgs.cpp
  src/log_reg_model_builder.pyx
  src/pickling.h
Labels: infra

#616 Refactoring package versions for build
  requirements-dev.txt
Labels: infra

#619 Add reference on benchmarks repo
  README.md
  doc/sources/index.rst
Labels: documentation

#623 Add conda-forge channel to README/Docs
  INSTALL.md
  README.md
  doc/sources/get_started.rst
Labels: documentation

#628 [Part1] support scikit-learn 1.0 version
  daal4py/sklearn/ensemble/_forest.py
  daal4py/sklearn/linear_model/_linear_0_24.py
  daal4py/sklearn/linear_model/_ridge_0_22.py
Labels: sklearn-patch, testing

#624 Add sklearnex modules; simple tests; support lists patching algorithms; align names with sklearn
  daal4py/sklearn/linear_model/__init__.py
  daal4py/sklearn/linear_model/_logistic_path_0_21.py
  daal4py/sklearn/linear_model/_logistic_path_0_22.py
  daal4py/sklearn/linear_model/logistic_path.py
  daal4py/sklearn/metrics/__init__.py
  daal4py/sklearn/metrics/_pairwise.py
  daal4py/sklearn/monkeypatch/_pairwise_0_21.py
  daal4py/sklearn/monkeypatch/_pairwise_0_22.py
  daal4py/sklearn/monkeypatch/dispatcher.py
  setup_sklearnex.py
  sklearnex/cluster/__init__.py
  sklearnex/cluster/dbscan.py
  sklearnex/cluster/k_means.py
  sklearnex/cluster/tests/test_dbscan.py
  sklearnex/cluster/tests/test_kmeans.py
  sklearnex/decomposition/__init__.py
  sklearnex/decomposition/pca.py
  sklearnex/decomposition/tests/test_pca.py
  sklearnex/dispatcher.py
  sklearnex/ensemble/__init__.py
  sklearnex/ensemble/forest.py
  sklearnex/ensemble/tests/test_random_forest.py
  sklearnex/linear_model/__init__.py
  sklearnex/linear_model/coordinate_descent.py
  sklearnex/linear_model/linear.py
  sklearnex/linear_model/logistic_path.py
  sklearnex/linear_model/ridge.py
  sklearnex/linear_model/tests/test_linear.py
  sklearnex/linear_model/tests/test_logreg.py
  sklearnex/manifold/__init__.py
  sklearnex/manifold/t_sne.py
  sklearnex/manifold/tests/test_tsne.py
  sklearnex/metrics/__init__.py
  sklearnex/metrics/pairwise.py
  sklearnex/metrics/ranking.py
  sklearnex/metrics/tests/test_metrics.py
  sklearnex/model_selection/__init__.py
  sklearnex/model_selection/split.py
  sklearnex/model_selection/tests/test_model_selection.py
  sklearnex/neighbors/__init__.py
  sklearnex/neighbors/knn_classification.py
  sklearnex/neighbors/knn_regression.py
  sklearnex/neighbors/knn_unsupervised.py
  sklearnex/neighbors/tests/test_neighbors.py
  sklearnex/svm/__init__.py
  sklearnex/svm/svm.py
  sklearnex/svm/tests/test_svm.py
  sklearnex/tests/_models_info.py
  sklearnex/tests/test_monkeypatch.py
Labels: sklearn-patch

#630 Update names for sklearn patching by algorithms; add tests
  daal4py/sklearn/monkeypatch/dispatcher.py
  daal4py/sklearn/monkeypatch/tests/test_monkeypatch.py
  sklearnex/dispatcher.py
  sklearnex/tests/test_monkeypatch.py
Labels: sklearn-patch, testing

#626 Infrastructure to run scikit-learn tests on GPU
  .circleci/deselect_tests.py
  .circleci/run_xpu_tests.py
  daal4py/sklearn/_utils.py
  deselected_tests.yaml
  generator/wrapper_gen.py
Labels: oneAPI

#629 Update short description and docs
  README.md
  doc/scikit-learn-acceration.png
  doc/sources/index.rst
  setup_sklearnex.py
Labels: documentation

#632 Fix typo in README.md
  README.md
Labels: documentation

#633 Add new failed tests to deselect due update numpy
  deselected_tests.yaml
Labels: testing

#636 Remove XGBoost notebook examples
  examples/XGBoost_Performance.ipynb
  examples/XGBoost_d4p_prediction.ipynb
Labels: examples

#639 [2021.2.1-rls] Cherry-pick for documentation
  INSTALL.md
  README.md
  daal4py/README.md
  doc/scikit-learn-acceration.png
  doc/sources/get_started.rst
  doc/sources/index.rst
  setup_sklearnex.py
Labels: documentation
