Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2021-07, with the labels that each got.

#710 replaced label with response
  onedal/svm/backend/svm_py.cpp
  onedal/svm/backend/svm_py.h
Labels: onedal iface

#713 Fix problem with sporadic failed for logreg sycl example
  examples/daal4py/sycl/log_reg_binary_dense_batch.py
Labels: examples

#709 Refactoring algos before scikit-learn 1.0
  daal4py/sklearn/cluster/_dbscan.py
  daal4py/sklearn/cluster/_k_means_0_22.py
  daal4py/sklearn/cluster/_k_means_0_23.py
  daal4py/sklearn/cluster/dbscan.py
  daal4py/sklearn/cluster/k_means.py
  daal4py/sklearn/decomposition/_pca.py
  daal4py/sklearn/ensemble/_forest.py
  daal4py/sklearn/linear_model/_coordinate_descent.py
  daal4py/sklearn/linear_model/_coordinate_descent_0_23.py
  daal4py/sklearn/linear_model/_linear.py
  daal4py/sklearn/linear_model/_linear_0_23.py
  daal4py/sklearn/linear_model/_linear_0_24.py
  daal4py/sklearn/linear_model/_ridge.py
  daal4py/sklearn/linear_model/coordinate_descent.py
  daal4py/sklearn/linear_model/linear.py
  daal4py/sklearn/linear_model/logistic_path.py
  daal4py/sklearn/linear_model/ridge.py
  daal4py/sklearn/manifold/_t_sne.py
  daal4py/sklearn/metrics/_ranking.py
  daal4py/sklearn/model_selection/_split.py
  deselected_tests.yaml
  sklearnex/dispatcher.py
Labels: sklearn-patch

#719 Fix conda-build for onedal ifaces
  setup.py
Labels: infra

#727 Revert building oneapi part for public CI
  .ci/pipeline/ci.yml
  setup.py
Labels: infra

#726 Changes before scikit-learn 1.0 [Ridge]
  daal4py/sklearn/linear_model/_ridge.py
Labels: sklearn-patch

#729 Add new article
  README.md
  doc/sources/index.rst
Labels: documentation

#730 Fix `get_number_of_types` failing with pandas dtypes
  daal4py/sklearn/_utils.py
Labels: sklearn-patch

#732 Fix ROC AUC data preprocessing
  daal4py/sklearn/metrics/_ranking.py
Labels: bug, sklearn-patch

#735 Revert pep8 ci
  .ci/pipeline/ci.yml
Labels: infra

#733 Add readme for notebook examples
  README.md
  examples/notebooks/README.md
Labels: documentation

#734 Add additional information for jupyter examples
  examples/notebooks/README.md
  examples/notebooks/knn_mnist.ipynb
  examples/notebooks/logistictic_regression_cifar.ipynb
  examples/notebooks/nusvr_medical_charges.ipynb
  examples/notebooks/random_forest_yolanda.ipynb
  examples/notebooks/svc_adult.ipynb
Labels: examples

#736 Add cast to list in getFPtype function
  daal4py/sklearn/_utils.py
Labels: bug

#737 Fix locate module paths
  .ci/pipeline/ci.yml
  conda-recipe/meta.yaml
  conda-recipe/run_test.sh
  daal4py/__init__.py
  daal4py/oneapi/__init__.py
  onedal/primitives/kernel_functions.py
  setup.py
  src/mpi/mpi_transceiver.cpp
  src/transceiver.cpp
Labels: bug, infra

#725 RF: fix tests
  daal4py/sklearn/ensemble/_forest.py
  daal4py/sklearn/ensemble/tests/test_decision_forest.py
  deselected_tests.yaml
  sklearnex/ensemble/tests/test_random_forest.py
  tests/test_examples.py
  tests/unittest_data/decision_forest_regression_batch.csv
Labels: sklearn-patch

#746 Fix jupyter job in nightly testing
  .ci/pipeline/nightly.yml
Labels: infra

#748 Fix releases CI
  .ci/pipeline/release.yml
Labels: infra

#747 Uncomment CSR test for SVM
  sklearnex/tests/test_run_to_run_stability_tests.py
Labels: testing

#752 Minor improve for reference in README
  README.md
Labels: documentation

#750 XGB model converter: data race fix
  src/gbt_convertors.pyx
Labels: bug

#749 add rpaths to onedal libraries in cmake
  onedal/__init__.py
  scripts/CMakeLists.txt
Labels: bug, infra, onedal iface
