Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2022-01, with the labels that each got.

#937 Exclude some tests for release CI
  .ci/pipeline/release.yml
Labels: testing

#941 Add information about daal4py in install.md file for sklearnex
  INSTALL.md
  doc/sources/installation.rst
Labels: documentation

#743 OneDAL python ifaces for kNN
  onedal/__init__.py
  onedal/common/_estimator_checks.py
  onedal/dal.cpp
  onedal/datatypes/__init__.py
  onedal/datatypes/numpy_helpers.hpp
  onedal/datatypes/validation.py
  onedal/neighbors/__init__.py
  onedal/neighbors/neighbors.cpp
  onedal/neighbors/neighbors.py
  onedal/neighbors/tests/test_knn_classification.py
  onedal/primitives/pairwise_distances.hpp
  onedal/svm/svm.py
  setup.py
  sklearnex/dispatcher.py
  sklearnex/neighbors/knn_classification.py
  sklearnex/neighbors/knn_unsupervised.py
  sklearnex/neighbors/tests/test_neighbors.py
Labels: onedal iface

#948 Fix sklearn tests [part 1]
  .circleci/deselect_tests.py
  daal4py/sklearn/_utils.py
  daal4py/sklearn/cluster/_dbscan.py
  daal4py/sklearn/cluster/_k_means_0_22.py
  daal4py/sklearn/cluster/_k_means_0_23.py
  daal4py/sklearn/decomposition/_pca.py
  daal4py/sklearn/ensemble/AdaBoostClassifier.py
  daal4py/sklearn/ensemble/_forest.py
  daal4py/sklearn/linear_model/_linear.py
  daal4py/sklearn/linear_model/logistic_path.py
  daal4py/sklearn/metrics/_pairwise.py
  daal4py/sklearn/model_selection/_split.py
  daal4py/sklearn/monkeypatch/__init__.py
  daal4py/sklearn/monkeypatch/dispatcher.py
  daal4py/sklearn/neighbors/_classification.py
  daal4py/sklearn/svm/_svm_0_22.py
  daal4py/sklearn/svm/_svm_0_23.py
  deselected_tests.yaml
  onedal/neighbors/neighbors.py
  sklearnex/neighbors/knn_classification.py
  sklearnex/neighbors/knn_unsupervised.py
  sklearnex/svm/_common.py
  sklearnex/svm/nusvc.py
  sklearnex/svm/nusvr.py
  sklearnex/svm/svc.py
  sklearnex/svm/svr.py
Labels: testing
