Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2023-09, with the labels that each got.

#1425 [feature] Refactor of ExtraTrees preview for eventual merge with Random Forest
  sklearnex/preview/ensemble/extra_trees.py
Labels: enhancement

#1446 Fixing the log_reg_model_builder_example
  examples/daal4py/log_reg_model_builder.py
  tests/run_examples.py
Labels: examples, model builders

#1472 Update lightGBM model builder example for LGBM v4
  examples/daal4py/model_builders_lightgbm.py
Labels: examples, model builders

#1473 FIX: Update xgboost model builder to fit changes in xgboost 2.0
  src/gbt_convertors.pyx
Labels: model builders

#1462 [bug] correct decision tree threshold default values for leaf nodes in daal4py and onedal
  onedal/primitives/tree_visitor.cpp
  src/tree_visitor.h
Labels: bug

#1492 Update README.md
  README.md
Labels: documentation

#1440 [Enhancement] Unify Random Forest and Extra Trees preview algorithms
  daal4py/sklearn/ensemble/_forest.py
  deselected_tests.yaml
  sklearnex/preview/ensemble/__init__.py
  sklearnex/preview/ensemble/_forest.py
  sklearnex/preview/ensemble/forest.py
  sklearnex/spmd/ensemble/forest.py
Labels: enhancement
