Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2023-10, with the labels that each got.

#1529 [testing, bug] fix table conversion issue with preview kmeans.fit when X is not contiguous
  onedal/cluster/kmeans.py
Labels: bug, testing

#1528 [testing, bug] include sklearn fallback for normal non-invertible matrices in preview linearRegression
  sklearnex/_utils.py
  sklearnex/preview/linear_model/linear.py
Labels: bug, testing

#1507 [testing] Fixing Extra Trees and Random Forest preview test_common.py issues
  onedal/primitives/get_tree.py
  sklearnex/preview/ensemble/_forest.py
Labels: enhancement, testing

#1535 Fix for floating point types support in train_test_split
  daal4py/sklearn/model_selection/_split.py
Labels: bug
