Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2024-06, with the labels that each got.

#1841 Remove main conda channel from Nightly and Release
  .ci/pipeline/nightly.yml
  .ci/pipeline/release.yml
Labels: dependencies

#1842 Add sklearn 1.5 to CI matrix
  .ci/pipeline/build-and-test-lnx.yml
  .ci/pipeline/ci.yml
  deselected_tests.yaml
  requirements-test.txt
  sklearnex/glob/dispatcher.py
  sklearnex/linear_model/logistic_regression.py
Labels: sklearn-patch, testing

#1859 Add sklearn 1.5 to CI matrix
  .ci/pipeline/build-and-test-lnx.yml
  .ci/pipeline/ci.yml
  deselected_tests.yaml
  requirements-test.txt
  sklearnex/glob/dispatcher.py
  sklearnex/linear_model/logistic_regression.py
Labels: sklearn-patch, testing, dependencies

#1846 Add CSR data support into BasicStatistics algorithm
  .ci/scripts/get_compatible_scipy_version.py
  onedal/basic_statistics/basic_statistics.cpp
  onedal/basic_statistics/basic_statistics.py
  onedal/basic_statistics/tests/test_basic_statistics.py
  onedal/cluster/kmeans.py
  onedal/datatypes/_data_conversion.py
  onedal/utils/__init__.py
  onedal/utils/validation.py
Labels: enhancement

#1862 CI: deselect failing sparse pandas test
  deselected_tests.yaml
Labels: testing

#1886 TEST: enable import tests for dataframes testing in `sklearnex.cluster.DBSCAN`
  sklearnex/cluster/tests/test_dbscan.py
Labels: testing

#1891 TEST: enabled different dataframe testing for linear models: `ElasticNet`, `Lasso`, `Ridge`
  sklearnex/linear_model/coordinate_descent.py
  sklearnex/linear_model/ridge.py
  sklearnex/linear_model/tests/test_linear.py
Labels: testing

#1903 CI: bump up `dpnp`/`dpctl` versions
  .ci/pipeline/build-and-test-lnx.yml
Labels: infra
