Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2024-08, with the labels that each got.

#1777 TEST: test coverage for sklearnex SPMD ifaces
  sklearnex/spmd/basic_statistics/tests/test_basic_statistics_spmd.py
  sklearnex/spmd/cluster/tests/test_dbscan_spmd.py
  sklearnex/spmd/cluster/tests/test_kmeans_spmd.py
  sklearnex/spmd/covariance/tests/test_covariance_spmd.py
  sklearnex/spmd/decomposition/tests/test_pca_spmd.py
  sklearnex/spmd/ensemble/tests/test_forest_spmd.py
  sklearnex/spmd/linear_model/tests/test_linear_regression_spmd.py
  sklearnex/spmd/linear_model/tests/test_logistic_regression_spmd.py
  sklearnex/spmd/neighbors/tests/test_neighbors_spmd.py
  sklearnex/tests/_utils_spmd.py
Labels: testing

#1990 Update oneDAL DPC interface detection
  INSTALL.md
  scripts/version.py
  setup.py
Labels: enhancement, onedal iface, dependencies

#1997 Update sklearn versions badge in README
  README.md
Labels: documentation

#2013 Logistic Regression CI fix
  sklearnex/linear_model/tests/test_logreg.py
Labels: testing
