Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2024-12, with the labels that each got.

#2192 [CI] change oneDAL organization reference for GitHub Actions CI
  .github/workflows/ci.yml
Labels: infra

#1925 ENH: Added serialization for IncrementalEmpiricalCovariance
  deselected_tests.yaml
  onedal/covariance/covariance.cpp
  onedal/covariance/incremental_covariance.py
  onedal/covariance/tests/test_incremental_covariance.py
  onedal/spmd/covariance/incremental_covariance.py
  sklearnex/covariance/incremental_covariance.py
  sklearnex/covariance/tests/test_incremental_covariance.py
Labels: enhancement

#1926 ENH: Added serialization for IncrementalPCA
  deselected_tests.yaml
  onedal/decomposition/incremental_pca.py
  onedal/decomposition/pca.cpp
  onedal/decomposition/tests/test_incremental_pca.py
  onedal/spmd/decomposition/incremental_pca.py
  sklearnex/preview/decomposition/incremental_pca.py
  sklearnex/preview/decomposition/tests/test_incremental_pca.py
Labels: enhancement

#2199 TEST: Adjust tolerance for IncrementalLinearRegression fp32 intercept
  onedal/linear_model/tests/test_incremental_linear_regression.py
Labels: testing

#2178 TEST: Re-enable GPU tests for decision trees
  deselected_tests.yaml
  sklearnex/ensemble/tests/test_forest.py
Labels: testing, gpu_interfaces

#2202 ci: resolve overdetermined CI issue
  sklearnex/linear_model/tests/test_linear.py
Labels: testing

#2204 TEST: Adjust tolerance for IncrementalLinearRegression fp32 coefficients
  onedal/linear_model/tests/test_incremental_linear_regression.py
Labels: testing

#2212 Disable patching for KMeans(n_clusters=1)
  sklearnex/cluster/k_means.py
Labels: bug, sklearn-patch

#2203 DOC: Update doc and internal links after uxl transfer
  .github/Pull_Request_template.md
  CONTRIBUTING.md
  INSTALL.md
  README.md
  SECURITY.md
  SUPPORT.md
  conda-recipe/meta.yaml
  daal4py/README.md
  deselected_tests.yaml
  doc/README.md
  doc/daal4py/_templates/layout.html
  doc/daal4py/algorithms.rst
  doc/daal4py/examples.rst
  doc/daal4py/index.rst
  doc/daal4py/model-builders.rst
  doc/daal4py/note.rst
  doc/daal4py/scaling.rst
  doc/daal4py/sklearn.rst
  doc/daal4py/streaming.rst
  doc/sources/404.rst
  doc/sources/_templates/layout.html
  doc/sources/algorithms.rst
  doc/sources/contribute.rst
  doc/sources/distributed-mode.rst
  doc/sources/index.rst
  doc/sources/license.rst
  doc/sources/quick-start.rst
  doc/sources/samples.rst
  doc/sources/support.rst
  examples/notebooks/ElasticNet.ipynb
  examples/notebooks/README.md
  examples/notebooks/dbscan.ipynb
  examples/notebooks/kmeans.ipynb
  examples/notebooks/knn_mnist.ipynb
  examples/notebooks/lasso_regression.ipynb
  examples/notebooks/linear_regression.ipynb
  examples/notebooks/logistictic_regression_cifar.ipynb
  examples/notebooks/nusvr_medical_charges.ipynb
  examples/notebooks/random_forest_yolanda.ipynb
  examples/notebooks/ridge_regression.ipynb
  examples/notebooks/svc_adult.ipynb
  examples/notebooks/tsne.ipynb
  scripts/CMakeLists.txt
  setup.py
  sklearnex/_utils.py
  sklearnex/dispatcher.py
Labels: documentation

#2205 DOC: Clear some warnings for daal4py doc builds
  .gitignore
  doc/daal4py/algorithms.rst
  doc/daal4py/conf.py
  doc/daal4py/index.rst
  doc/daal4py/model-builders.rst
Labels: documentation

#2220 FIX (FTI) model converter for lightGBM models
  src/gbt_convertors.pyx
Labels: bug, model builders

#2226 DOC : Fix misrendered docstrings in `IncrementalLinearRegression`
  sklearnex/linear_model/incremental_linear.py
Labels: documentation

#2230 TEST: Use deterministic seeds in tests
  onedal/utils/tests/test_validation.py
  sklearnex/utils/tests/test_validation.py
Labels: testing
