Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2024-09, with the labels that each got.

#2022 [fix] Add forgotten _check_array to IncrementalBasicStatistics.partial_fit
  onedal/basic_statistics/incremental_basic_statistics.py
Labels: bug

#1770 KMeans OOP
  deselected_tests.yaml
  onedal/cluster/kmeans.cpp
  onedal/cluster/kmeans.py
  onedal/cluster/kmeans_init.cpp
  onedal/cluster/kmeans_init.py
  setup.py
  sklearnex/cluster/__init__.py
  sklearnex/cluster/k_means.py
  sklearnex/cluster/tests/test_kmeans.py
  sklearnex/dispatcher.py
  sklearnex/preview/__init__.py
  sklearnex/preview/cluster/__init__.py
  sklearnex/preview/cluster/_common.py
  sklearnex/preview/cluster/k_means.py
  sklearnex/tests/test_patching.py
  sklearnex/tests/test_run_to_run_stability.py
Labels: enhancement

#2053 fix int overflow in FTI model convertor
  src/gbt_convertors.pyx
Labels: model builders

#2063 oneMKL migration: Fix for DLL loading issue on Windows
  daal4py/__init__.py
Labels: infra

#2064 TEST: clear a few warnings in model builder tests
  tests/test_df_support.py
  tests/test_model_builders.py
Labels: testing

#2066 oneMKL migration: Temporary deselection of tests
  deselected_tests.yaml
  onedal/svm/tests/test_csr_svm.py
  onedal/svm/tests/test_nusvr.py
  onedal/svm/tests/test_svr.py
  sklearnex/cluster/tests/test_kmeans.py
  sklearnex/linear_model/tests/test_incremental_linear.py
  tests/test_daal4py_examples.py
Labels: testing

#2069 Use `__repr__` method for `daal4py` algorithm results in order to be printable in jupyter sessions
  generator/wrapper_gen.py
  tests/test_printing.py
Labels: enhancement

#2074 Fix for getting of description for PR Checklist job
  .github/workflows/pr-checklist.yml
Labels: infra
