Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2024-07, with the labels that each got.

#1888 TEST: enable import tests for dataframes testing in `sklearnex.cluster.Kmeans`
  sklearnex/cluster/k_means.py
  sklearnex/cluster/tests/test_kmeans.py
Labels: testing

#1908 Fix for Logistic Regression loss scaling
  daal4py/sklearn/linear_model/logistic_path.py
  deselected_tests.yaml
Labels: bug, sklearn-patch

#1892 TEST: using `pytest.skip` instead of `device_filter`
  onedal/datatypes/tests/test_data.py
  onedal/ensemble/tests/test_random_forest.py
  onedal/neighbors/tests/test_knn_classification.py
  onedal/primitives/tests/test_kernel_functions.py
  onedal/svm/tests/test_svc.py
  onedal/tests/utils/_dataframes_support.py
  onedal/tests/utils/_device_selection.py
  sklearnex/ensemble/tests/test_forest.py
  sklearnex/linear_model/tests/test_logreg.py
  sklearnex/svm/tests/test_svm.py
Labels: testing

#1937 Fix: Remove accidentally pushed comment from IncPCA example.
  examples/sklearnex/incremental_pca_dpctl.py
Labels: examples

#1934 Enable PCA deselected test
  deselected_tests.yaml
Labels: testing

#1924 ENH: Renamed layout check macro for np.array, changed default layout for oneDAL table
  onedal/datatypes/data_conversion.cpp
  onedal/datatypes/numpy_helpers.hpp
  src/daal4py.cpp
Labels: enhancement

#1942 FIX: Remove exit code check from tests/test_examples_sklearnex.py to get meaningful logs
  tests/test_examples_sklearnex.py
Labels: bug, testing

#1940 FIX: prevent `support_usm_ndarray` from changing queue if explicitly provided.
  onedal/_device_offload.py
Labels: bug

#1953 Fix on preview ridge tests having too little error tolerance for coefficients assertions
  sklearnex/preview/linear_model/tests/test_ridge.py
Labels: sklearn-patch, testing

#1956 Update PR template
  .ci/pipeline/ci.yml
  .ci/pipeline/docs.yml
  .github/Pull_Request_template.md
Labels: documentation

#1955 Unify daal4py and sklearnex building
  .ci/pipeline/build-and-test-lnx.yml
  .ci/pipeline/build-and-test-mac.yml
  .ci/pipeline/build-and-test-win.yml
  .ci/pipeline/docs.yml
  .ci/pipeline/nightly.yml
  INSTALL.md
  daal4py/INSTALL.md
  daal4py/README.md
  setup.cfg
  setup.py
  setup_sklearnex.cfg
  setup_sklearnex.py
Labels: enhancement, sklearn-patch
