Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2024-11, with the labels that each got.

#2083 ENH: Enable accelerated linear regression for overdetermined systems
  deselected_tests.yaml
  doc/sources/algorithms.rst
  onedal/linear_model/tests/test_linear_regression.py
  onedal/utils/validation.py
  sklearnex/linear_model/linear.py
  sklearnex/linear_model/tests/test_linear.py
Labels: enhancement

#2145 DOC: Intel MPI GPU offload update
  doc/sources/distributed-mode.rst
Labels: documentation

#2149 TEST: disabled GPU test case
  deselected_tests.yaml
Labels: bug

#2130 DOC: Fix docs related to `n_jobs`
  daal4py/sklearn/_n_jobs_support.py
  doc/sources/conf.py
  sklearnex/basic_statistics/basic_statistics.py
  sklearnex/basic_statistics/incremental_basic_statistics.py
Labels: documentation

#2135 TEST: Fix json report for MPI
  conda-recipe/run_test.bat
  conda-recipe/run_test.sh
  tests/helper_mpi_tests.py
Labels: testing

#2155 Add documentation for preview module
  doc/sources/index.rst
  doc/sources/preview.rst
Labels: documentation

#2162 Set token permission for ci.yml
  .github/workflows/ci.yml
  .github/workflows/pr-checklist.yml
  .github/workflows/renovate-validation.yml
Labels: oneAPI

#2160 Update of DPC dependencies for CI and conda-recipe
  .ci/pipeline/build-and-test-lnx.yml
  .ci/scripts/install_dpcpp.sh
  conda-recipe/meta.yaml
Labels: infra, dependencies

#2171 MAINT: Add vscode workspace files to gitignore
  .gitignore
Labels: enhancement

#2173 DOC: Mention build requirements for distributed mode
  INSTALL.md
Labels: documentation

#2170 MAINT: Implement option to oneDAL's lib path to sklearnex's RPATH
  INSTALL.md
  scripts/CMakeLists.txt
  scripts/build_backend.py
  setup.py
Labels: enhancement

#2176 Python 3.13 support
  .ci/pipeline/ci.yml
  daal4py/sklearn/_n_jobs_support.py
  requirements-test.txt
Labels: enhancement

#2184 [enhancement] remove string comparison from data type oneDAL offload
  onedal/basic_statistics/basic_statistics.py
  onedal/cluster/dbscan.py
  onedal/cluster/kmeans.py
  onedal/cluster/kmeans_init.py
  onedal/common/dispatch_utils.hpp
  onedal/covariance/covariance.py
  onedal/datatypes/table.cpp
  onedal/decomposition/pca.py
  onedal/ensemble/forest.py
  onedal/linear_model/linear_model.py
  onedal/linear_model/logistic_regression.py
  onedal/neighbors/neighbors.py
  onedal/primitives/kernel_functions.py
  onedal/svm/svm.py
  sklearnex/spmd/cluster/tests/test_kmeans_spmd.py
Labels: enhancement

#2185 [enhancement] remove contiguous check from ```_check_array```
  onedal/datatypes/_data_conversion.py
  onedal/datatypes/data_conversion.cpp
  onedal/datatypes/data_conversion_sua_iface.cpp
  onedal/datatypes/tests/test_data.py
  onedal/datatypes/utils/sua_iface_helpers.cpp
  onedal/utils/validation.py
Labels: enhancement

#2193 DOC: Add note about potential TBB linkage clashes
  INSTALL.md
Labels: documentation

#2126 [enhancement] add oneDAL finiteness_checker implementation to onedal
  onedal/dal.cpp
  onedal/utils/finiteness_checker.cpp
  onedal/utils/tests/test_validation.py
  onedal/utils/validation.py
  sklearnex/utils/tests/test_finite.py
Labels: enhancement

#2167 ENH: Enable linear regression on GPU with non-PSD systems
  deselected_tests.yaml
  doc/sources/algorithms.rst
  onedal/linear_model/tests/test_linear_regression.py
  sklearnex/linear_model/linear.py
  sklearnex/linear_model/tests/test_incremental_linear.py
  sklearnex/linear_model/tests/test_linear.py
  sklearnex/spmd/linear_model/tests/test_incremental_linear_spmd.py
Labels: bug, gpu_interfaces
