Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2024-05, with the labels that each got.

#1821 Update python to 3.11 in Docs CI job
  .ci/pipeline/docs.yml
Labels: documentation, dependencies

#1825 Fix DPNP/DPCTL F-contiguous data processing
  sklearnex/_device_offload.py
Labels: bug

#1800 [enhancement, testing] add initial array_api testing capabilities using array-api-strict
  onedal/tests/utils/_dataframes_support.py
  requirements-test.txt
  sklearnex/conftest.py
Labels: Array API
