Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2024-10, with the labels that each got.

#2067 Enable serialization in `daal4py` algorithm classes
  generator/wrapper_gen.py
  tests/test_daal4py_serialization.py
Labels: enhancement

#2075 MAINT: increase tests timeout to `170`
  tests/test_daal4py_examples.py
Labels: testing

#2081 CI: broaden kmeans 2025.0 deselections
  deselected_tests.yaml
Labels: testing

#2070 oneMKL migration: Cherry-picking commits from #2063 and #2066 into 2025.0 release branch
  daal4py/__init__.py
  deselected_tests.yaml
  onedal/svm/tests/test_csr_svm.py
  onedal/svm/tests/test_nusvr.py
  onedal/svm/tests/test_svr.py
  sklearnex/cluster/tests/test_kmeans.py
  sklearnex/linear_model/tests/test_incremental_linear.py
  tests/test_daal4py_examples.py
Labels: testing

#2091 Fixes for PR checklist workflow
  .github/workflows/pr-checklist.yml
Labels: infra

#2079 ENH: adding `array-api-compat` and enabling array api conformance tests
  deselected_tests.yaml
  requirements-test.txt
Labels: enhancement, Array API

#2094 [fix] address additional intermittent KNN failure in GitHub Nightly build CI
  sklearnex/tests/test_run_to_run_stability.py
Labels: infra

#2090 TEST: Run all tests through `pytest`
  .ci/scripts/test_global_patch.py
  conda-recipe/meta.yaml
  conda-recipe/run_test.bat
  conda-recipe/run_test.sh
  tests/__init__.py
  tests/test_examples_sklearnex.py
Labels: testing

#2103 DOC: Add info about incremental algorithms and BS
  doc/sources/algorithms.rst
  doc/sources/conf.py
  doc/sources/index.rst
  doc/sources/non-scikit-algorithms.rst
  sklearnex/basic_statistics/basic_statistics.py
  sklearnex/basic_statistics/incremental_basic_statistics.py
  sklearnex/covariance/incremental_covariance.py
  sklearnex/linear_model/incremental_linear.py
Labels: documentation

#2111 [fix] make design_rule trace data more user-friendly in ```test_common.py```
  sklearnex/tests/test_common.py
Labels: infra

#2115 [fix] lock 'isort' and 'black' matching versions for pre-commit-config.yaml and CI check
  .ci/pipeline/ci.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
Labels: infra

#2093 [enhancement] interface with compressed artifacts oneapi-src/oneDAL#2938
  .github/scripts/activate_components.bat
  .github/workflows/ci.yml
Labels: enhancement, infra

#2118 TEST: increase timeout for gradient_boosted_classification
  tests/test_daal4py_examples.py
Labels: testing

#2108 TEST: increase threshold for memory usage on tests
  sklearnex/tests/test_memory_usage.py
Labels: testing

#1992 [enh] Conda recipe update and CI OS version pinning
  .ci/pipeline/build-and-test-win.yml
  .ci/pipeline/ci.yml
  .ci/pipeline/nightly.yml
  .ci/scripts/gen_release_jobs.py
  .github/workflows/ci.yml
  INSTALL.md
  conda-recipe/bld.bat
  conda-recipe/build.sh
  conda-recipe/conda_build_config.yaml
  conda-recipe/meta.yaml
  conda-recipe/run_test.bat
  conda-recipe/run_test.sh
  scripts/CMakeLists.txt
Labels: infra

#2107 TEST: Produce JSON logs from pytest runs
  .ci/pipeline/build-and-test-lnx.yml
  .ci/pipeline/build-and-test-win.yml
  .github/workflows/ci.yml
  .gitignore
  conda-recipe/run_test.bat
  conda-recipe/run_test.sh
  requirements-test.txt
Labels: testing

#1867 MAINT: using common test primitive for banned primitives check in locations
  onedal/tests/test_common.py
  sklearnex/tests/test_common.py
Labels: testing

#1751 FEAT(forest): hyperparameter support for RF clf inference
  daal4py/sklearn/_utils.py
  onedal/common/dispatch_utils.hpp
  onedal/common/hyperparameters.py
  onedal/ensemble/forest.cpp
  onedal/ensemble/forest.py
  sklearnex/ensemble/_forest.py
  sklearnex/ensemble/tests/test_forest.py
Labels: enhancement, onedal iface

#2056 [fix] correct logic k-NN algos ```kneighbors()``` call when ```algorithm='brute'``` and fit with GPU
  onedal/neighbors/neighbors.py
  sklearnex/neighbors/tests/test_neighbors.py
Labels: bug

#2127 Provide additional explanation for checkboxes in PR template
  .github/Pull_Request_template.md
Labels: documentation

#2133 DOC: Describe support and behavior for different input types
  doc/sources/index.rst
  doc/sources/input-types.rst
Labels: documentation

#1907 ENH: fallback to stock `scikit-learn` after `onedal` fail
  .circleci/run_xpu_tests.py
  onedal/_config.py
  sklearnex/_config.py
  sklearnex/conftest.py
  sklearnex/linear_model/linear.py
  sklearnex/linear_model/logistic_regression.py
  sklearnex/tests/test_config.py
Labels: enhancement

#2134 DOC: Clear warnings when building docs
  doc/build-doc.sh
  doc/sources/conf.py
  doc/sources/kaggle/classification.rst
  doc/sources/samples.rst
Labels: documentation, examples
