Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2025-06, with the labels that each got.

#2473 DOC: Add instructions for building with ASAN
  INSTALL.md
Labels: documentation, infra

#2510 DOC: Fix incorrect italics formatting
  doc/sources/quick-start.rst
Labels: documentation

#2451 Fixes for sklearn 1.7 pre-release support
  daal4py/sklearn/ensemble/_forest.py
  daal4py/sklearn/manifold/_t_sne.py
  daal4py/sklearn/metrics/_pairwise.py
  onedal/ensemble/forest.py
  onedal/utils/_array_api.py
Labels: bug, sklearn-patch

#2354 update: update algorithm.rst based on current implementation
  doc/sources/algorithms.rst
  sklearnex/basic_statistics/incremental_basic_statistics.py
  sklearnex/covariance/incremental_covariance.py
  sklearnex/linear_model/incremental_linear.py
  sklearnex/linear_model/incremental_ridge.py
Labels: documentation

#2544 DOC: Update tags and docs for sklearn1.7
  README.md
  doc/sources/quick-start.rst
Labels: documentation

#2521 fix: minor basic stats quality fixes
  examples/sklearnex/basic_statistics_spmd.py
  onedal/basic_statistics/basic_statistics.py
Labels: enhancement

#2540 FIX: Fix table destructor not being called
  onedal/datatypes/numpy/data_conversion.cpp
  onedal/datatypes/table.cpp
Labels: bug

#2491 DOC: Reword description about patching in preview mode
  doc/sources/non-scikit-algorithms.rst
  doc/sources/preview.rst
Labels: documentation

#2571 Update ubuntu CI image to 24.04
  .ci/pipeline/ci.yml
  .ci/pipeline/docs.yml
  .ci/pipeline/nightly.yml
  .ci/scripts/gen_release_jobs.py
  .pre-commit-config.yaml
Labels: infra, dependencies

#2464 DOC: Better explanations about GPGPU driver installations
  README.md
  doc/sources/index.rst
  doc/sources/oneapi-gpu.rst
  doc/sources/quick-start.rst
Labels: documentation
