Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2025-04, with the labels that each got.

#2397 FIX: Fix incorrect logic for detecting intel compilers in setup file
  setup.py
Labels: infra

#2398 FIX: Fix unpropagated `I_MPI_ROOT` as replacement for `MPIROOT`.
  scripts/build_backend.py
  setup.py
Labels: infra

#2392 FIX: Don't corrupt XGB objects when converting them
  daal4py/mb/gbt_convertors.py
  tests/test_model_builders.py
Labels: model builders

#2400 ENH: Add public-facing properties to model builder class to query type of model
  daal4py/mb/model_builders.py
Labels: model builders

#2403 MAINT: Remove unused files for 'distributed logreg' and 'lbfgs'
  src/dist_logistic_regression_training.h
  src/lbfgs.cpp
Labels: infra

#2401 FIX: Fix docs about enums listing incorrect acceptable values
  generator/wrapper_gen.py
Labels: documentation

#2421 FIX: Allow weights as positional argument in BasicStatistics
  sklearnex/basic_statistics/basic_statistics.py
Labels: bug

#2420 MAINT: Inherit docstrings instead of copy-pasting them
  sklearnex/neighbors/_lof.py
  sklearnex/svm/nusvc.py
Labels: infra

#2427 MAINT: Enable black formatting for all python versions
  pyproject.toml
Labels: infra

#2395 DOC: Document selected daal4py sections in sklearnex, add full API reference section
  README.md
  daal4py/mb/logistic_regression_builders.py
  doc/daal4py/scaling.rst
  doc/sources/about_daal4py.rst
  doc/sources/conf.py
  doc/sources/d4p-kmeans-scale.jpg
  doc/sources/daal4py.rst
  doc/sources/distributed-mode.rst
  doc/sources/distributed_daal4py.rst
  doc/sources/index.rst
  doc/sources/model_builders.rst
  doc/sources/model_builders_speedup.webp
  doc/sources/non-scikit-algorithms.rst
  doc/sources/non_sklearn_d4p.rst
  doc/sources/quick-start.rst
  doc/sources/substitutions.rst
Labels: documentation, examples

#2423 ENH: Parallelize doc build by default
  doc/Makefile
Labels: documentation, infra

#2426 TEST: Update catboost version
  requirements-test.txt
Labels: testing

#2428 Fix multiclass SVM example failures on AVX2
  examples/daal4py/svm_multiclass.py
Labels: examples

#2399 FIX: Respect user-supplied `$CXX`
  INSTALL.md
  scripts/build_backend.py
  setup.py
Labels: infra

#2419 FIX, MAINT: Migrate model builders tests to pytest + bugfixes
  daal4py/mb/gbt_convertors.py
  daal4py/mb/tree_based_builders.py
  doc/sources/daal4py.rst
  doc/sources/model_builders.rst
  tests/test_model_builders.py
Labels: bug, testing, model builders

#2411 DOC: Showcase usage without patching in readme
  README.md
  doc/sources/index.rst
Labels: documentation

#2443 MAINT: Remove unreachable code section in model builders
  daal4py/mb/tree_based_builders.py
Labels: model builders

#2438 fix: raise an error when arguments are not provided as list
  onedal/tests/utils/_device_selection.py
Labels: enhancement
