Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2025-07, with the labels that each got.

#2465 Support for sklearn 1.6 conformance testing
  daal4py/sklearn/linear_model/logistic_path.py
  deselected_tests.yaml
  onedal/linear_model/linear_model.py
  sklearnex/linear_model/ridge.py
Labels: testing, dependencies

#2594 Fix: Find libs in $DALROOT with conda-style paths
  scripts/version.py
Labels: bug

#2580 Deselect specific sparse elkan tests
  deselected_tests.yaml
Labels: testing

#2592 FIX: Install scikit-learn in doc deployment CI job
  .github/workflows/docs-release.yml
Labels: bug

#2595 FIX: Specify namespace for std types
  src/daal4py.cpp
  src/daal4py.h
  src/transceiver.h
Labels: bug

#2610 FIX: Fix double division of logistic model regularization by sum of weights
  daal4py/sklearn/linear_model/logistic_loss.py
  sklearnex/linear_model/tests/test_logreg.py
Labels: bug

#2561 Add the ability to reset hyperparameters
  onedal/common/hyperparameters.py
  sklearnex/__init__.py
  sklearnex/_utils.py
  sklearnex/decomposition/pca.py
  sklearnex/decomposition/tests/test_pca.py
  sklearnex/ensemble/_forest.py
  sklearnex/ensemble/tests/test_forest.py
  sklearnex/linear_model/incremental_linear.py
  sklearnex/linear_model/linear.py
  sklearnex/linear_model/tests/test_linear.py
  sklearnex/preview/covariance/covariance.py
  sklearnex/preview/covariance/tests/test_covariance.py
  sklearnex/tests/test_hyperparameters.py
Labels: enhancement

#2612 enhancement: enable array API support in DBSCAN
  onedal/cluster/dbscan.py
  sklearnex/cluster/dbscan.py
  sklearnex/spmd/cluster/dbscan.py
Labels: Array API

#2623 fix(circleci): correct argument type for `--json-report-file`
  .circleci/run_xpu_tests.py
Labels: bug, infra, python

#2626 sklearn 1.7.0 for doc reqs
  requirements-doc.txt
Labels: bug, documentation, dependencies

#2628 FIX: Fix incorrect processing of logistic regularization when passed to sklearn
  daal4py/sklearn/linear_model/logistic_path.py
  daal4py/sklearn/linear_model/tests/test_logreg.py
Labels: bug

#2615 Add support for local trees mode in forest
  onedal/ensemble/forest.cpp
  onedal/spmd/ensemble/forest.py
  sklearnex/spmd/ensemble/forest.py
  sklearnex/spmd/ensemble/tests/test_forest_spmd.py
Labels: enhancement, distributed

#2638 DOC: Better instructions for MPI dependencies
  doc/sources/distributed-mode.rst
  doc/sources/distributed_daal4py.rst
  doc/sources/quick-start.rst
Labels: documentation
