Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2025-05, with the labels that each got.

#2466 DOC: Configure single backticks to render as code to mimic sklearn
  doc/sources/conf.py
Labels: documentation

#2460 feature: check dead links in doc CI
  doc/build-doc.sh
  doc/sources/conf.py
  doc/sources/daal4py.rst
  examples/notebooks/svc_adult.ipynb
  examples/notebooks/tsne.ipynb
Labels: documentation

#2472 FIX: Revert location of versions.json
  doc/sources/conf.py
Labels: documentation, infra

#2475 DOC: More details for conda installs
  INSTALL.md
  doc/sources/distributed-mode.rst
  doc/sources/distributed_daal4py.rst
  doc/sources/quick-start.rst
Labels: documentation

#2484 fix: add cstdint include to transceiver for public CI
  src/transceiver.h
Labels: bug

#2487 MAINT: Empty commit to `gh-pages` to retrigger deployment
  versions.json
Labels: infra

#2390 [enhancement] unify policy creation in pybind11
  onedal/common/_backend.py
  onedal/common/policy.cpp
  onedal/common/spmd_policy.cpp
  onedal/dal.cpp
Labels: enhancement
