Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2025-01, with the labels that each got.

#2245 TEST: Backport adjustments to linear regression tolerances
  onedal/linear_model/tests/test_incremental_linear_regression.py
Labels: testing

#2256 DOC: Clarify requirement on clang-format
  INSTALL.md
Labels: documentation

#2257 DOC: Clarify requirement on oneDAL version
  INSTALL.md
Labels: documentation

#2255 TEST: Use absolute tolerance as linear regresion criterion
  onedal/linear_model/tests/test_incremental_linear_regression.py
Labels: testing

#2259 DOC: Update note about supported setups
  INSTALL.md
Labels: documentation

#2258 TEST: Backport absolute tolerance criterion
  onedal/linear_model/tests/test_incremental_linear_regression.py
Labels: testing

#2261 DOC: Fix misrendered URL link in daal4py docs
  doc/daal4py/index.rst
Labels: documentation

#2262 MAINT: Add package tag indicating python3.13 support
  setup.py
Labels: documentation

#2265 Pin py-lief dependency version to fix LinuxCondaRecipe
  .ci/pipeline/conda-recipe-lnx.yml
Labels: dependencies

#2253 Add sklearnex.BasicStatistics API for CSR inputs on GPU and a test for it
  onedal/basic_statistics/basic_statistics.py
  onedal/basic_statistics/tests/utils.py
  sklearnex/basic_statistics/basic_statistics.py
  sklearnex/basic_statistics/tests/test_basic_statistics.py
  sklearnex/tests/test_run_to_run_stability.py
  sklearnex/tests/utils/__init__.py
  sklearnex/tests/utils/base.py
Labels: gpu_interfaces

#2278 Revert "Pin py-lief dependency version to fix LinuxCondaRecipe (#2265)"
  .ci/pipeline/conda-recipe-lnx.yml
Labels: dependencies

#2283 DOC: Update `daal4py` .md instructions file
  daal4py/README.md
Labels: documentation

#2279 DOC: Fix version switcher code and update URLs and logos
  .github/.licenserc.yaml
  doc/build-doc.sh
  doc/sources/_static/custom.css
  doc/sources/_static/favicon.png
  doc/sources/_static/favicons.png
  doc/sources/_static/oneAPI-rgb-rev-100.png
  doc/sources/_static/uxl-foundation-logo-horizontal-color.png
  doc/sources/_static/version_switcher.js
  doc/sources/_templates/layout.html
  doc/sources/_templates/versions.html
  doc/sources/conf.py
  doc/versions.json
Labels: documentation

#2285 fix: incremental pca example patching logic
  examples/sklearnex/incremental_pca_dpctl.py
Labels: sklearn-patch, examples

#2291 MAINT: Remove accidentally committed file
  examples/notebooks/NYCTaxi-E2E-Demo/NYCTaxi-E2E-RAPIDS.ipynb
Labels: examples
