Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2025-08, with the labels that each got.

#2643 MAINT: Set `-e` mode in doc CI to catch errors
  .ci/pipeline/docs.yml
Labels: infra

#2614 MAINT: Deselect failing tests for logistic regression
  deselected_tests.yaml
Labels: testing

#2639 FIX, MAINT: Offload LogisticRegression to sklearn when oneDAL is not used, fix various issues
  daal4py/sklearn/linear_model/logistic_path.py
  daal4py/sklearn/linear_model/tests/test_logreg.py
  deselected_tests.yaml
  doc/sources/algorithms.rst
  sklearnex/linear_model/tests/test_logreg.py
Labels: bug

#2653 MAINT: Relax test conditions for log-probabilities in model builders
  tests/test_model_builders.py
Labels: testing

#2207 [Enhancement] enable array API support in ```EmpiricialCovariance``` and ```IncrementalEmpiricalCovariance```
  onedal/covariance/covariance.py
  onedal/covariance/incremental_covariance.py
  onedal/covariance/tests/test_covariance.py
  sklearnex/covariance/incremental_covariance.py
  sklearnex/covariance/tests/test_incremental_covariance.py
  sklearnex/preview/covariance/covariance.py
  sklearnex/spmd/covariance/covariance.py
  sklearnex/spmd/covariance/tests/test_covariance_spmd.py
  sklearnex/spmd/covariance/tests/test_incremental_covariance_spmd.py
  sklearnex/utils/_array_api.py
Labels: Array API

#2106 ENH: `PCA` via Array API based on #2096
  .ci/scripts/select_sklearn_tests.py
  deselected_tests.yaml
  onedal/decomposition/incremental_pca.py
  onedal/decomposition/pca.py
  onedal/decomposition/tests/test_incremental_pca.py
  sklearnex/decomposition/pca.py
  sklearnex/decomposition/tests/test_pca.py
  sklearnex/preview/decomposition/incremental_pca.py
  sklearnex/preview/decomposition/tests/test_incremental_pca.py
  sklearnex/spmd/decomposition/pca.py
  sklearnex/spmd/decomposition/tests/test_incremental_pca_spmd.py
  sklearnex/spmd/decomposition/tests/test_pca_spmd.py
  sklearnex/tests/test_common.py
  sklearnex/tests/test_patching.py
Labels: enhancement, Array API

#2665 FIX: Avoid re-usage of non-reusable daal4py objects
  daal4py/mb/logistic_regression_builders.py
  doc/sources/about_daal4py.rst
  tests/test_model_builders.py
Labels: bug

#2650 FIX: Fix error on decision function with GPU arrays
  onedal/linear_model/logistic_regression.py
  sklearnex/linear_model/logistic_regression.py
  sklearnex/linear_model/tests/test_logreg.py
Labels: bug, gpu_interfaces, Array API

#2673 DOC: Add ridge to list of GPU support
  doc/sources/algorithms.rst
Labels: documentation

#2675 Update PR template
  .github/Pull_Request_template.md
Labels: enhancement
