Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2025-09, with the labels that each got.

#2679 FIX: Don't change SCIPY_ARRAY_API at runtime
  .ci/scripts/run_sklearn_tests.py
  .circleci/run_xpu_tests.py
  sklearnex/_config.py
Labels: Array API

#2681 DOC: Correct argument names for additional tree parameters
  doc/sources/guide/acceleration.rst
Labels: documentation

#2703 MAINT: Remove double assignment
  onedal/linear_model/logistic_regression.py
Labels: python

#2557 Add NearestNeighbors SPMD API
  onedal/neighbors/neighbors.py
  onedal/spmd/neighbors/__init__.py
  onedal/spmd/neighbors/neighbors.py
  sklearnex/spmd/neighbors/__init__.py
  sklearnex/spmd/neighbors/tests/test_neighbors_spmd.py
Labels: enhancement, distributed
