Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2025-02, with the labels that each got.

#2295 ENH: Accept `I_MPI_ROOT` as fallback to `MPIROOT`
  INSTALL.md
  setup.py
Labels: dependencies

#2299 FIX: Fix html widget docs links
  sklearnex/_utils.py
  sklearnex/cluster/dbscan.py
  sklearnex/cluster/k_means.py
  sklearnex/decomposition/pca.py
  sklearnex/ensemble/_forest.py
  sklearnex/linear_model/linear.py
  sklearnex/linear_model/logistic_regression.py
  sklearnex/linear_model/ridge.py
  sklearnex/manifold/t_sne.py
  sklearnex/neighbors/common.py
  sklearnex/preview/covariance/covariance.py
  sklearnex/preview/decomposition/incremental_pca.py
  sklearnex/svm/_common.py
Labels: enhancement

#2300 DOC: Add incremental ridge to docs
  doc/sources/non-scikit-algorithms.rst
  sklearnex/linear_model/incremental_ridge.py
Labels: documentation

#2286 DOC: Clarify requirements for running on GPU and supported configurations
  README.md
  doc/sources/algorithms.rst
  doc/sources/conf.py
  doc/sources/distributed-mode.rst
  doc/sources/index.rst
  doc/sources/oneapi-gpu.rst
  doc/sources/quick-start.rst
  doc/sources/substitutions.rst
Labels: documentation

#2320 ci: increase gbt classification example timeout
  tests/test_daal4py_examples.py
Labels: testing

#2326 fix: use utf-8 encoding
  tests/run_examples.py
Labels: bug

#2153 [experiment] ENH: using only raw inputs for onedal backend
  onedal/_config.py
  onedal/_device_offload.py
  onedal/basic_statistics/basic_statistics.py
  onedal/basic_statistics/incremental_basic_statistics.py
  onedal/cluster/dbscan.py
  onedal/cluster/kmeans.py
  onedal/covariance/covariance.py
  onedal/covariance/incremental_covariance.py
  onedal/decomposition/incremental_pca.py
  onedal/decomposition/pca.py
  onedal/ensemble/forest.py
  onedal/linear_model/incremental_linear_model.py
  onedal/linear_model/linear_model.py
  onedal/linear_model/logistic_regression.py
  onedal/neighbors/neighbors.py
  onedal/utils/_array_api.py
  onedal/utils/_dpep_helpers.py
  sklearnex/_config.py
  sklearnex/_device_offload.py
  sklearnex/basic_statistics/incremental_basic_statistics.py
  sklearnex/cluster/dbscan.py
  sklearnex/covariance/incremental_covariance.py
  sklearnex/ensemble/_forest.py
  sklearnex/linear_model/incremental_linear.py
  sklearnex/preview/decomposition/incremental_pca.py
  sklearnex/spmd/basic_statistics/tests/test_basic_statistics_spmd.py
  sklearnex/spmd/basic_statistics/tests/test_incremental_basic_statistics_spmd.py
  sklearnex/spmd/cluster/tests/test_dbscan_spmd.py
  sklearnex/spmd/cluster/tests/test_kmeans_spmd.py
  sklearnex/spmd/covariance/tests/test_covariance_spmd.py
  sklearnex/spmd/covariance/tests/test_incremental_covariance_spmd.py
  sklearnex/spmd/decomposition/tests/test_incremental_pca_spmd.py
  sklearnex/spmd/decomposition/tests/test_pca_spmd.py
  sklearnex/spmd/ensemble/tests/test_forest_spmd.py
  sklearnex/spmd/linear_model/tests/test_incremental_linear_spmd.py
  sklearnex/spmd/linear_model/tests/test_linear_regression_spmd.py
  sklearnex/spmd/linear_model/tests/test_logistic_regression_spmd.py
  sklearnex/spmd/neighbors/tests/test_neighbors_spmd.py
Labels: enhancement, distributed

#2327 DOC: Removed unused `dpctl` import in examples
  README.md
  doc/sources/index.rst
Labels: documentation
