Repository uxlfoundation/scikit-learn-intelex, pull requests merged in 2025-03, with the labels that each got.

#2333 DOC: Update instructions for building docs
  doc/README.md
Labels: documentation

#2332 MAINT: Add a warning not to modify auto-generated files
  .github/.licenserc.yaml
  doc/Makefile
  doc/daal4py/Makefile
  doc/daal4py/make.bat
  doc/make.bat
Labels: documentation, infra

#2340 chore: update documentation on config parameters
  onedal/_config.py
  sklearnex/_config.py
Labels: documentation

#2356 DOC: Incorporate PR review suggestions
  INSTALL.md
  doc/sources/conf.py
  doc/sources/oneapi-gpu.rst
  doc/sources/quick-start.rst
Labels: documentation

#2316 ENH: Add new parameters for linear regression
  onedal/linear_model/linear_model.cpp
  sklearnex/linear_model/tests/test_linear.py
Labels: enhancement

#2370 Deselection for forest RNG oneDAL update
  deselected_tests.yaml
Labels: testing

#2380 DOC: Document full extent of extension estimators
  doc/sources/non-scikit-algorithms.rst
  sklearnex/linear_model/incremental_linear.py
Labels: documentation

#2379 DOC: Fix various formatting issues
  doc/daal4py/index.rst
  doc/daal4py/model-builders.rst
  doc/daal4py/scaling.rst
Labels: documentation

#2385 MAINT: Reuse docstring from sklearn classes instead of copy-pastying in extension estimators
  sklearnex/basic_statistics/incremental_basic_statistics.py
  sklearnex/covariance/incremental_covariance.py
  sklearnex/linear_model/incremental_linear.py
  sklearnex/linear_model/incremental_ridge.py
Labels: documentation

#2381 DOC: Use common variable for serialization note
  daal4py/sklearn/_n_jobs_support.py
  sklearnex/_utils.py
  sklearnex/basic_statistics/incremental_basic_statistics.py
  sklearnex/covariance/incremental_covariance.py
  sklearnex/linear_model/incremental_linear.py
  sklearnex/linear_model/incremental_ridge.py
  sklearnex/preview/decomposition/incremental_pca.py
Labels: documentation

#2387 Fix for misuse of sklearnex verbosity
  onedal/common/_backend.py
Labels: bug

#2346 Enhance sklearn 1.7 support and remove sklearn<1.0 code
  .ci/scripts/get_compatible_scipy_version.py
  daal4py/sklearn/cluster/dbscan.py
  daal4py/sklearn/cluster/k_means.py
  daal4py/sklearn/decomposition/_pca.py
  daal4py/sklearn/ensemble/AdaBoostClassifier.py
  daal4py/sklearn/ensemble/GBTDAAL.py
  daal4py/sklearn/ensemble/_forest.py
  daal4py/sklearn/linear_model/_coordinate_descent.py
  daal4py/sklearn/linear_model/_linear.py
  daal4py/sklearn/linear_model/_ridge.py
  daal4py/sklearn/linear_model/logistic_path.py
  daal4py/sklearn/manifold/_t_sne.py
  daal4py/sklearn/metrics/_pairwise.py
  daal4py/sklearn/neighbors/_base.py
  daal4py/sklearn/neighbors/_classification.py
  daal4py/sklearn/neighbors/_regression.py
  daal4py/sklearn/svm/svm.py
  daal4py/sklearn/utils/base.py
  daal4py/sklearn/utils/validation.py
  onedal/utils/_dpep_helpers.py
  onedal/utils/validation.py
  sklearnex/_device_offload.py
  sklearnex/basic_statistics/basic_statistics.py
  sklearnex/basic_statistics/incremental_basic_statistics.py
  sklearnex/cluster/dbscan.py
  sklearnex/cluster/k_means.py
  sklearnex/covariance/incremental_covariance.py
  sklearnex/decomposition/pca.py
  sklearnex/dispatcher.py
  sklearnex/ensemble/_forest.py
  sklearnex/linear_model/incremental_linear.py
  sklearnex/linear_model/incremental_ridge.py
  sklearnex/linear_model/linear.py
  sklearnex/linear_model/logistic_regression.py
  sklearnex/linear_model/ridge.py
  sklearnex/neighbors/_lof.py
  sklearnex/neighbors/common.py
  sklearnex/neighbors/knn_classification.py
  sklearnex/neighbors/knn_regression.py
  sklearnex/neighbors/knn_unsupervised.py
  sklearnex/preview/covariance/covariance.py
  sklearnex/preview/decomposition/incremental_pca.py
  sklearnex/svm/_common.py
  sklearnex/svm/nusvc.py
  sklearnex/svm/nusvr.py
  sklearnex/svm/svc.py
  sklearnex/svm/svr.py
  sklearnex/tests/test_common.py
  sklearnex/utils/validation.py
Labels: sklearn-patch

#2386 FIX: Fix incorrect scale of base_score being used for XGB regression objectives
  src/gbt_convertors.pyx
  tests/test_model_builders.py
Labels: model builders

#2384 DOC: Document model builders, settings, and helper functions in daal4py
  daal4py/mb/__init__.py
  daal4py/mb/model_builders.py
  doc/daal4py/conf.py
  doc/daal4py/contents.rst
  doc/daal4py/helpers.rst
  doc/daal4py/model-builders.rst
  doc/daal4py/scaling.rst
  generator/wrapper_gen.py
Labels: documentation

#2391 ENH: Don't cythonize pure-python GBT conversion code
  daal4py/mb/gbt_convertors.py
  daal4py/mb/model_builders.py
  generator/gen_daal4py.py
  tests/test_model_builders.py
Labels: model builders

#2393 ci: fix Jupyter CI job fail
  .ci/pipeline/nightly.yml
Labels: bug, dependencies
